# Generated by Django 6.0.1 on 2026-01-10 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('keyword', models.CharField(max_length=200)),
                ('footer', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('order', models.SmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('link', models.ManyToManyField(blank=True, to='common.link')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='page_builder.page')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='profiles/img/')),
                ('image_badge', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=255)),
                ('organisation', models.TextField()),
                ('org_short_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('badge', models.CharField(max_length=255)),
                ('link', models.ManyToManyField(blank=True, to='common.link')),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page_builder.profile'),
        ),
        migrations.CreateModel(
            name='SubComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('order', models.SmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcomponents', to='page_builder.component')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('list', 'List'), ('numbered_list', 'Numbered List'), ('image', 'Image'), ('link', 'Link')], default='text', max_length=50)),
                ('data', models.JSONField(blank=True, null=True)),
                ('order', models.SmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('subcomponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='page_builder.subcomponent')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
