# Generated by Django 6.0.1 on 2026-01-30 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('keyword', models.CharField(blank=True, max_length=200, null=True)),
                ('footer', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('order', models.SmallIntegerField(default=0)),
                ('layout', models.CharField(choices=[('publications', 'Publications'), ('cards', 'Cards'), ('grid', 'Grid'), ('timeline', 'Timeline'), ('showcase', 'Showcase'), ('centered', 'Centered'), ('links', 'Links'), ('default', 'Default')], default='default', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('link', models.ManyToManyField(blank=True, to='common.link')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='page_builder.page')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profiles/img/')),
                ('image_badge', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('organisation', models.TextField(blank=True, null=True)),
                ('org_short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('badge', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('link', models.ManyToManyField(to='common.link')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page_builder.profile'),
        ),
        migrations.CreateModel(
            name='SubComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.SmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_components', to='page_builder.component')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('list', 'List'), ('numbered_list', 'Numbered List'), ('image', 'Image'), ('link', 'Link')], default='text', max_length=50)),
                ('data', models.JSONField(blank=True, null=True)),
                ('order', models.SmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('subcomponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='page_builder.subcomponent')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
