# Generated by Django 6.0.1 on 2026-01-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_initial'),
        ('page_builder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='link',
            field=models.ManyToManyField(blank=True, null=True, to='common.link'),
        ),
        migrations.AlterField(
            model_name='subcomponent',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
