# Generated by Django 6.0.1 on 2026-01-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_builder', '0002_alter_profile_link_alter_subcomponent_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/img/'),
        ),
    ]
