# Generated by Django 6.0.1 on 2026-01-10 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_builder', '0003_alter_contentblock_data_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcomponent',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_components', to='page_builder.component'),
        ),
    ]
