# Generated by Django 6.0.1 on 2026-01-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_builder', '0005_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
