# Generated by Django 6.0.1 on 2026-01-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_builder', '0006_alter_page_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='footer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='keyword',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
