# Generated by Django 6.0.1 on 2026-01-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_builder', '0008_remove_profile_name_profile_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='layout',
            field=models.CharField(choices=[('publications', 'Publications'), ('cards', 'Cards'), ('grid', 'Grid'), ('timeline', 'Timeline'), ('showcase', 'Showcase'), ('centered', 'Centered'), ('links', 'Links'), ('default', 'Default')], default='default'),
        ),
    ]
