# Generated by Django 6.0.1 on 2026-01-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_builder', '0009_component_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
