# Generated by Django 6.0.1 on 2026-01-10 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('page_builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page_builder.profile'),
        ),
        migrations.AddField(
            model_name='contact',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.icon'),
        ),
        migrations.AddField(
            model_name='stat',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.icon'),
        ),
        migrations.AddField(
            model_name='stat',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.link'),
        ),
        migrations.AddField(
            model_name='stat',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page_builder.profile'),
        ),
    ]
